apiVersion: v1
kind: Pod
metadata:
  name: krane-agent
  annotations: 
    service-profile: cloud-ar-vr
spec:
 schedulerName: krane-cloud-ar-vr 
 restartPolicy: Never
 containers:
 - name: krane-agent
   image: 220.149.13.178:5050/krane-agent:revision_v0.99
   args: 
   - -l=4
   - -pod=192.168.5.1
   - -node=220.149.13.193
   - -p=5001:5001/udp
   - -s=initial
   - -i=dumonet/iperf2:etri
   - -n=iperf
   - -c=/bin/bash ./tmp/iperf2.sh 220.149.13.179
   securityContext:
     privileged: true
   volumeMounts:
   - name: dockersock
     mountPath: /var/run/docker.sock
   - name: host-container
     mountPath: /var/lib/docker/
   - name: nfs
     mountPath: /mnt/nfs
 volumes:
 - name: dockersock
   hostPath:
     path: /var/run/docker.sock
 - name: host-container
   hostPath:
     path: /var/lib/docker/containers
 - name: nfs
   hostPath:
     path: /mnt/nfs
