apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "krane.fullname" . }}-extender-config
  namespace: kube-system
  labels:
    app: {{ include "krane.name" . }}
    chart: {{ include "krane.chart" . }}
    release: {{ .Release.Name }}
data:
  extenderConfig.json : {{ .Values.extenderConfig | toJson | quote }}
