apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "krane.fullname" . }}
  namespace: kube-system
  labels:
    app: {{ include "krane.name" . }}
    chart: {{ include "krane.chart" . }}
    release: {{ .Release.Name }}
