# Default values for sample-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  scheduler:   
    repository: jrlee/kube-scheduler-with-logging
    tag: 0.0.4
    pullPolicy: IfNotPresent
  extender:
    repository: 220.149.13.178:5050/krane-scheduler  
    tag: 1.04
    pullPolicy: IfNotPresent

configuration:
  logLevel: 5
  configFile: "/extender/extenderConfig.json"
  apiServerIpAddr: "220.149.13.191:9999"
  podName: "krane-agent"
  mountPath: /extender

extenderConfig:
  {
    "NetworkUtilizationLatencyFunc":{
      "1":0.018, 
      "2":0.018,
      "3":0.018,
      "4":0.018, 
      "5":0.018,
      "6":0.018,
      "7":0.018, 
      "8":0.018, 
      "9":0.018,
      "10":0.018,
      "11":0.018, 
      "12":0.018,
      "13":0.018,
      "14":0.018, 
      "15":0.018,
      "16":0.018,
      "17":0.018, 
      "18":0.018, 
      "19":0.018,
      "20":0.018,
      "21":0.018, 
      "22":0.018,
      "23":0.018,
      "24":0.018, 
      "25":0.018,
      "26":0.018,
      "27":0.018, 
      "28":0.018, 
      "29":0.018,
      "30":0.018,
      "31":0.018, 
      "32":0.018,
      "33":0.018,
      "34":0.018, 
      "35":0.018,
      "36":0.018,
      "37":0.018, 
      "38":0.018, 
      "39":0.018,
      "40":0.018,
      "41":0.018, 
      "42":0.018,
      "43":0.018,
      "44":0.018, 
      "45":0.018,
      "46":0.018,
      "47":0.018, 
      "48":0.018, 
      "49":0.018,
      "50":0.018,
      "51":0.018, 
      "52":0.018,
      "53":0.018,
      "54":0.018, 
      "55":0.018,
      "56":0.018,
      "57":0.018, 
      "58":0.018, 
      "59":0.018,
      "60":0.018,
      "61":0.018, 
      "62":0.018,
      "63":0.018,
      "64":0.018, 
      "65":0.018,
      "66":0.018,
      "67":0.018, 
      "68":0.018, 
      "69":0.018,
      "70":0.018,
      "71":0.018, 
      "72":0.018,
      "73":0.018,
      "74":0.018, 
      "75":0.018,
      "76":0.018,
      "77":0.018, 
      "78":0.018, 
      "79":0.018,
      "80":0.018,
      "81":0.018, 
      "82":0.018,
      "83":0.018,
      "84":0.018, 
      "85":0.018,
      "86":0.034,
      "87":0.033,
      "88":0.033,
      "89":0.033,
      "90":1.830,
      "91":2.240,
      "92":2.760,
      "93":2.650,
      "94":2.920,
      "95":2.890,
      "96":2.360,
      "97":3.170,
      "98":3.180
    },
    "Prometheus" : {
      "Https" : false,
      "Host" : "220.149.13.191",
      "Port" : "31957",
      "NodeExporterPort" : "9100",
      "NetworkDevices" : {
        "kube-node1" : "ens3",
        "kube-node2" : "ens3",
	"kube-node3" : "ens3"
      },
      "NodeNICSpeeds": {
        "kube-node1" : 100,
        "kube-node2" : 100,
	"kube-node3" : 100
      }
    },
    "ServiceProfile" : {
      "LimitUtilizationOfLowGroup": 20,
      "LimitUtilizationOfMediumGroup": 40,
      "LimitUtilizationOfHighGroup": 60
    }
  }

