apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "krane.fullname" . }}-cloud-ar-vr-scheduler-config
  namespace: kube-system
  labels:
    app: {{ include "krane.name" . }}
    chart: {{ include "krane.chart" . }}
    release: {{ .Release.Name }}
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: {{ .Release.Name }}-cloud-ar-vr
    algorithmSource:
      policy:
        configMap:
          namespace: kube-system
          name: {{ include "krane.fullname" . }}-cloud-ar-vr-policy
    leaderElection:
      leaderElect: true
      lockObjectName: {{ .Release.Name }}-cloud-ar-vr 
      lockObjectNamespace: kube-system
